/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora.view;

import javax.swing.JOptionPane;
import locadora.dao.FilmeDAO;
import locadora.enums.EGenero;
import locadora.model.Filme;

/**
 *
 * @author steph
 */
public class CadastrarFilme extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarFilme
     */
    public CadastrarFilme() {
        initComponents();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLTitulo = new javax.swing.JLabel();
        JLSubTitulo = new javax.swing.JLabel();
        JLNome = new javax.swing.JLabel();
        JTNome = new javax.swing.JTextField();
        JLAno = new javax.swing.JLabel();
        JTAno = new javax.swing.JTextField();
        JLGenero = new javax.swing.JLabel();
        JBSalvar = new javax.swing.JButton();
        JCGenero = new javax.swing.JComboBox<>();
        JBVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JLTitulo.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        JLTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/locadora.png"))); // NOI18N
        JLTitulo.setText("Locadora Castellano");

        JLSubTitulo.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        JLSubTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/filme.png"))); // NOI18N
        JLSubTitulo.setText("Cadastrar Filme");

        JLNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLNome.setText("Nome: ");

        JLAno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLAno.setText("Ano:");

        JLGenero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLGenero.setText("Genero:");

        JBSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/salvar.png"))); // NOI18N
        JBSalvar.setText("Salvar");
        JBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalvarActionPerformed(evt);
            }
        });

        JCGenero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JCGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JCGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCGeneroActionPerformed(evt);
            }
        });

        JBVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/voltar.png"))); // NOI18N
        JBVoltar.setText("Voltar");
        JBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBVoltar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JLAno)
                                    .addComponent(JLNome)
                                    .addComponent(JLGenero))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTAno, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JCGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(JLSubTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(JBSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JLTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLSubTitulo)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLNome))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLAno)
                    .addComponent(JTAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarActionPerformed
        try{
            if(!"".equals(JTNome.getText()) && !"".equals(JTAno.getText()))
            {
                String nome = JTNome.getText();
                int ano = Integer.parseInt(JTAno.getText());
                String genero = (String) JCGenero.getSelectedItem();                
                EGenero egenero = EGenero.valueOf(genero);

                Filme filme;
                
                FilmeDAO filmeDAO = new FilmeDAO();
                
                if(operacao == null){
                    filme = new Filme(0, nome, ano, egenero, true);
                    filmeDAO.salvar(filme);
                }
                else if(operacao.equals("Editar")){
                    filme = new Filme(filmeGlobal.getId(), nome, ano, egenero, filmeGlobal.getDisponivel());
                    filmeDAO.alterar(filme);
                }
                
                JOptionPane.showMessageDialog(null, "Salvo com Sucesso!!!");
                setVisible(false);
            }
            else {
                JOptionPane.showMessageDialog(null, "Campos Nome, ano e genero sao obrigatórios.");
            }  
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_JBSalvarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        preencheCombo();
    }//GEN-LAST:event_formWindowOpened

    private void JCGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCGeneroActionPerformed

    private void JBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVoltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_JBVoltarActionPerformed

    String[] dados = {"ACAO", "FICCAO", "AVENTURA", "TERROR", "ROMANCE", "COMEDIA", "DOCUMENTARIO",
    "INFANTIL", "INFATOJUVENIL", "MUSICAL", "ADULTO"};
    
    private void preencheCombo() {        
        
        JCGenero.removeAllItems(); 

        for(int i = 0; i < dados.length; i++) {
            JCGenero.addItem(dados[i]);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBSalvar;
    private javax.swing.JButton JBVoltar;
    private javax.swing.JComboBox<String> JCGenero;
    private javax.swing.JLabel JLAno;
    private javax.swing.JLabel JLGenero;
    private javax.swing.JLabel JLNome;
    private javax.swing.JLabel JLSubTitulo;
    private javax.swing.JLabel JLTitulo;
    private javax.swing.JTextField JTAno;
    private javax.swing.JTextField JTNome;
    // End of variables declaration//GEN-END:variables

    private Filme filmeGlobal;
    private String operacao;
    
    void preparedEdit(Filme fil, String op) {
        this.filmeGlobal = fil;
        this.operacao = op;

        JTNome.setText(filmeGlobal.getNome());
        JTAno.setText(filmeGlobal.getAno() + "");
        JCGenero.setSelectedItem(filmeGlobal.getGenero()); 
    }
}
