/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora.view;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import locadora.dao.ClienteDAO;
import locadora.dao.FilmeDAO;
import locadora.dao.LocacaoDAO;
import locadora.dao.TipoValorDAO;
import locadora.model.Cliente;
import locadora.model.Filme;
import locadora.model.Locacao;
import locadora.model.TipoValor;

/**
 *
 * @author steph
 */
public class CadastrarLocacao extends javax.swing.JFrame {

    /**
     * Creates new form AlugarFilme
     */
    public CadastrarLocacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLTitulo = new javax.swing.JLabel();
        JLSubTitulo = new javax.swing.JLabel();
        JLCliente = new javax.swing.JLabel();
        JLFilme = new javax.swing.JLabel();
        JCFilme = new javax.swing.JComboBox<>();
        JLDataLocacao = new javax.swing.JLabel();
        JLDataDevolucao = new javax.swing.JLabel();
        JLValor = new javax.swing.JLabel();
        JCValor = new javax.swing.JComboBox<>();
        JBSalvar = new javax.swing.JButton();
        JBVoltar = new javax.swing.JButton();
        JCCliente = new javax.swing.JComboBox<>();
        JTDataLocacao = new javax.swing.JTextField();
        JTDataDevolucao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JLTitulo.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        JLTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/locadora.png"))); // NOI18N
        JLTitulo.setText("Locadora Castellano");

        JLSubTitulo.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        JLSubTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/novalocacao.png"))); // NOI18N
        JLSubTitulo.setText("Locação");

        JLCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLCliente.setText("Cliente:");

        JLFilme.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLFilme.setText("Filme:");

        JCFilme.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JCFilme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        JLDataLocacao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLDataLocacao.setText("Data de Locação:");

        JLDataDevolucao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLDataDevolucao.setText("Data da Devolução");

        JLValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLValor.setText("Valor");

        JCValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JCValor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        JBSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/salvar.png"))); // NOI18N
        JBSalvar.setText("Salvar");
        JBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalvarActionPerformed(evt);
            }
        });

        JBVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/voltar.png"))); // NOI18N
        JBVoltar.setText("Voltar");
        JBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVoltarActionPerformed(evt);
            }
        });

        JCCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JCCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(JBSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JLTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JLCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(JLDataLocacao))
                                    .addComponent(JLFilme)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JLDataDevolucao))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JLValor)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JCCliente, 0, 163, Short.MAX_VALUE)
                            .addComponent(JCFilme, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JCValor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTDataLocacao)
                            .addComponent(JTDataDevolucao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(JLSubTitulo)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JBVoltar)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JLTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLSubTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLFilme))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLDataLocacao)
                    .addComponent(JTDataLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLDataDevolucao)
                    .addComponent(JTDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLValor))
                .addGap(32, 32, 32)
                .addComponent(JBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(JBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVoltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_JBVoltarActionPerformed

    private void JBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarActionPerformed
        try{
            if(!"".equals(JTDataLocacao.getText()) && !"".equals(JTDataDevolucao.getText()))
            {
                int idxCliente = (int) JCCliente.getSelectedIndex();
                int idxFilme = (int) JCFilme.getSelectedIndex();
                // Date dataLocacao = new Date(JTDataLocacao.getText());
                //Date dataDevolucao = new Date(JTDataLocacao.getText());
                SimpleDateFormat stf = new SimpleDateFormat("dd/MM/yyyy");
                
                Date dataLocacao = stf.parse(JTDataLocacao.getText());
                Date dataDevolucao = stf.parse(JTDataDevolucao.getText());
                int idxTipoValor = (int) JCValor.getSelectedIndex(); 

                Cliente cliente = clientes.get(idxCliente);
                Filme filme = filmes.get(idxFilme);
                TipoValor tipoValor = valores.get(idxTipoValor);
                
                Locacao locacao;
                
                LocacaoDAO locacaoDAO = new LocacaoDAO();
                
                if(operacao == null){
                    locacao = new Locacao(0, cliente, filme, tipoValor, dataLocacao, dataDevolucao);
                    locacaoDAO.salvar(locacao);
                }
                else if(operacao.equals("Editar")){
                    locacao = new Locacao(locacaoGlobal.getId(), cliente, filme, tipoValor, dataLocacao, dataDevolucao);
                    locacaoDAO.alterar(locacao);
                }
                
                JOptionPane.showMessageDialog(null, "Salvo com Sucesso!!!");
                setVisible(false);
            }
            else {
                JOptionPane.showMessageDialog(null, "Campos data de locaçao e data de devoluçao sao obrigatórios.");
            }  
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_JBSalvarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            preencheCombo();
        } catch (SQLException ex) {
            Logger.getLogger(CadastrarLocacao.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CadastrarLocacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private ArrayList<Cliente> clientes;
    private ArrayList<Filme> filmes;
    private ArrayList<TipoValor> valores;
    
    private void preencheCombo() throws SQLException, ClassNotFoundException {        
        
        clientes = new ClienteDAO().buscarTodos();
        filmes = new FilmeDAO().buscarTodos();
        valores = new TipoValorDAO().buscarTodos();
        
        JCCliente.removeAllItems(); 
        JCFilme.removeAllItems();
        JCValor.removeAllItems();

        for(int i = 0; i < clientes.size(); i++) {
            JCCliente.addItem(clientes.get(i).getNome());
        }
        
        for(int i = 0; i < filmes.size(); i++) {
            JCFilme.addItem(filmes.get(i).getNome());
        }
        
        for(int i = 0; i < valores.size(); i++) {
            JCValor.addItem(valores.get(i).getDescricao() + " - R$ " + valores.get(i).getValor());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarLocacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBSalvar;
    private javax.swing.JButton JBVoltar;
    private javax.swing.JComboBox<String> JCCliente;
    private javax.swing.JComboBox<String> JCFilme;
    private javax.swing.JComboBox<String> JCValor;
    private javax.swing.JLabel JLCliente;
    private javax.swing.JLabel JLDataDevolucao;
    private javax.swing.JLabel JLDataLocacao;
    private javax.swing.JLabel JLFilme;
    private javax.swing.JLabel JLSubTitulo;
    private javax.swing.JLabel JLTitulo;
    private javax.swing.JLabel JLValor;
    private javax.swing.JTextField JTDataDevolucao;
    private javax.swing.JTextField JTDataLocacao;
    // End of variables declaration//GEN-END:variables

    private Locacao locacaoGlobal;
    private String operacao;
    
    void preparedEdit(Locacao loc, String op) {
        this.locacaoGlobal = loc;
        this.operacao = op;

        JCCliente.setSelectedItem(locacaoGlobal.getCliente());
        JCFilme.setSelectedItem(locacaoGlobal.getFilme());
        JTDataLocacao.setText(locacaoGlobal.getDataLocacao().toString());
        JTDataDevolucao.setText(locacaoGlobal.getDataDevolucao().toString());
        JCValor.setSelectedItem(locacaoGlobal.getTipoValor());
    }
}
