/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora.view;

import javax.swing.JOptionPane;
import locadora.dao.TipoValorDAO;
import locadora.model.TipoValor;

/**
 *
 * @author steph
 */
public class CadastrarValores extends javax.swing.JFrame {

    /**
     * Creates new form TipoValor
     */
    public CadastrarValores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLTitulo = new javax.swing.JLabel();
        JLSubTitulo = new javax.swing.JLabel();
        JLDescricao = new javax.swing.JLabel();
        JLValor = new javax.swing.JLabel();
        JTDescricao = new javax.swing.JTextField();
        JTValor = new javax.swing.JTextField();
        JBSalvar = new javax.swing.JButton();
        JBVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLTitulo.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        JLTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/locadora.png"))); // NOI18N
        JLTitulo.setText("Locadora Castellano");

        JLSubTitulo.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        JLSubTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/money.png"))); // NOI18N
        JLSubTitulo.setText("Tabela Valores");

        JLDescricao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLDescricao.setText("Descrição:");

        JLValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLValor.setText("Valor:");

        JBSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/salvar.png"))); // NOI18N
        JBSalvar.setText("Salvar");
        JBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalvarActionPerformed(evt);
            }
        });

        JBVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/voltar.png"))); // NOI18N
        JBVoltar.setText("Voltar");
        JBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(JLTitulo)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLValor)
                            .addComponent(JLDescricao))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTValor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBSalvar)))
                    .addComponent(JLSubTitulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBVoltar)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JLTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLSubTitulo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLDescricao)
                    .addComponent(JTDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLValor)
                    .addComponent(JTValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(JBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(JBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarActionPerformed
        try{
            if(!"".equals(JTDescricao.getText()) && !"".equals(JTValor.getText()))
            {
                String descricao = JTDescricao.getText();
                double valor = Double.parseDouble(JTValor.getText());  
  
                TipoValor tipoValor;
                
                TipoValorDAO tipoValorDAO = new TipoValorDAO();
                
                if(operacao == null){
                    tipoValor = new TipoValor(0, descricao, valor);
                    tipoValorDAO.salvar(tipoValor);
                }
                else if(operacao.equals("Editar")){
                    tipoValor = new TipoValor(tipoValorGlobal.getId(), descricao, valor);
                    tipoValorDAO.alterar(tipoValor);
                }
                
                JOptionPane.showMessageDialog(null, "Operação realizada com Sucesso!!!");
                setVisible(false);
            }
            else {
                JOptionPane.showMessageDialog(null, "Campos descricao e valor sao obrigatórios.");
            }  
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_JBSalvarActionPerformed

    private void JBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVoltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_JBVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoValor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoValor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoValor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoValor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarValores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBSalvar;
    private javax.swing.JButton JBVoltar;
    private javax.swing.JLabel JLDescricao;
    private javax.swing.JLabel JLSubTitulo;
    private javax.swing.JLabel JLTitulo;
    private javax.swing.JLabel JLValor;
    private javax.swing.JTextField JTDescricao;
    private javax.swing.JTextField JTValor;
    // End of variables declaration//GEN-END:variables

    private TipoValor tipoValorGlobal;
    private String operacao;
    
    void preparedEdit(TipoValor tp, String op) {
        this.tipoValorGlobal = tp;
        this.operacao = op;

        JTDescricao.setText(tipoValorGlobal.getDescricao());
        JTValor.setText(tipoValorGlobal.getValor() + "");
    }
}
