/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadora.dao.FilmeDAO;
import locadora.model.Filme;

/**
 *
 * @author steph
 */
public class ListFilme extends javax.swing.JFrame {

    /**
     * Creates new form ListFilme
     */
    public ListFilme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLTitulo = new javax.swing.JLabel();
        JLSubTitulo = new javax.swing.JLabel();
        JLNome = new javax.swing.JLabel();
        JBPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTabela = new javax.swing.JTable();
        JTNome = new javax.swing.JTextField();
        JBAlterar = new javax.swing.JButton();
        JBExcluir = new javax.swing.JButton();
        JBVoltar = new javax.swing.JButton();
        JBNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JLTitulo.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        JLTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/locadora.png"))); // NOI18N
        JLTitulo.setText("Locadora Castellano");

        JLSubTitulo.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        JLSubTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/filme.png"))); // NOI18N
        JLSubTitulo.setText("Filmes");

        JLNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLNome.setText("Nome:");

        JBPesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/pesquisar.png"))); // NOI18N
        JBPesquisar.setText("Pesquisar");
        JBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPesquisarActionPerformed(evt);
            }
        });

        JTabela.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Ano", "Genero", "Disponivel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTabela);

        JBAlterar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/atualizar.png"))); // NOI18N
        JBAlterar.setText("Alterar");
        JBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAlterarActionPerformed(evt);
            }
        });

        JBExcluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/excluir.png"))); // NOI18N
        JBExcluir.setText("Excluir");
        JBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBExcluirActionPerformed(evt);
            }
        });

        JBVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/voltar.png"))); // NOI18N
        JBVoltar.setText("Voltar");
        JBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVoltarActionPerformed(evt);
            }
        });

        JBNovo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/novo.png"))); // NOI18N
        JBNovo.setText("Novo");
        JBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLSubTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addComponent(JBPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(JLTitulo)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBVoltar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBAlterar)
                                .addGap(31, 31, 31)
                                .addComponent(JBExcluir)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLSubTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNome)
                    .addComponent(JTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(JBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            preencheTable();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ListCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void JBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVoltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_JBVoltarActionPerformed

    private void JBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNovoActionPerformed
        CadastrarFilme tela = new CadastrarFilme();
        tela.setVisible(true);
    }//GEN-LAST:event_JBNovoActionPerformed

    private void JBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAlterarActionPerformed
        final int idx = JTabela.getSelectedRow();

        if (idx < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um filme!!!");
        } else {
            CadastrarFilme tela = new CadastrarFilme();
            tela.preparedEdit(listaFilmes.get(idx), "Editar");
            tela.setVisible(true);       
        }
    }//GEN-LAST:event_JBAlterarActionPerformed

    private void JBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBExcluirActionPerformed
        final int idx = JTabela.getSelectedRow();

        if (idx < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um filme!!!");
        } else {
            Filme filme = listaFilmes.get(idx);    
            FilmeDAO filmeDAO = new FilmeDAO();
            
            try {
                filmeDAO.apagar(filme);
                listaFilmes.remove(idx);
                JOptionPane.showMessageDialog(null, "Operação realizada com sucesso!!!");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }            
        }
    }//GEN-LAST:event_JBExcluirActionPerformed

    private void JBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPesquisarActionPerformed
        if("".equals(JTNome.getText())){            
            try {
                preencheTable();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ListCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            DefaultTableModel dftm = (DefaultTableModel) JTabela.getModel();

            while (dftm.getRowCount() > 0) {
                dftm.removeRow(0);
            }

            String nome = JTNome.getText();
            Filme  filme = new Filme();
            
            try {
                filme = new FilmeDAO().buscarPeloNome(nome);
            } catch (SQLException ex) {
                Logger.getLogger(ListFilme.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ListFilme.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            listaFilmes = new ArrayList<Filme>();
            listaFilmes.add(filme);
            
            if(filme == null || filme.getId() == 0){
                JOptionPane.showMessageDialog(null, "Nenhum filme encontrado por esse nome");
            }
            else{
                for (Filme f : listaFilmes) {
                    String[] coluna = new String[5];
                    coluna[0] = f.getId() + "";
                    coluna[1] = f.getNome();
                    coluna[2] = f.getAno() + "";
                    coluna[3] = f.getGenero().toString();
                    coluna[4] = f.getDisponivel() + "";
                    dftm.addRow(coluna);
                }
            }
        }
    }//GEN-LAST:event_JBPesquisarActionPerformed
    
    
    private void preencheTable() throws ClassNotFoundException {
        DefaultTableModel dftm = (DefaultTableModel) JTabela.getModel();

        while (dftm.getRowCount() > 0) {
            dftm.removeRow(0);
        }

        try {
            listaFilmes = new FilmeDAO().buscarTodos();
            for (Filme f : listaFilmes) {
                String[] coluna = new String[5];
                coluna[0] = f.getId() + "";
                coluna[1] = f.getNome();
                coluna[2] = f.getAno() + "";
                coluna[3] = f.getGenero().toString();
                coluna[4] = f.getDisponivel() + "";                
                dftm.addRow(coluna);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar os filmes");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAlterar;
    private javax.swing.JButton JBExcluir;
    private javax.swing.JButton JBNovo;
    private javax.swing.JButton JBPesquisar;
    private javax.swing.JButton JBVoltar;
    private javax.swing.JLabel JLNome;
    private javax.swing.JLabel JLSubTitulo;
    private javax.swing.JLabel JLTitulo;
    private javax.swing.JTextField JTNome;
    private javax.swing.JTable JTabela;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
    private ArrayList<Filme> listaFilmes;
}
