/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadora.dao.ClienteDAO;
import locadora.model.Cliente;

/**
 *
 * @author steph
 */
public class ListCliente extends javax.swing.JFrame {

    /**
     * Creates new form ListCliente
     */
    public ListCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLTitulo = new javax.swing.JLabel();
        JLSubTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTabela = new javax.swing.JTable();
        JLCpf = new javax.swing.JLabel();
        JTCpf = new javax.swing.JTextField();
        JBPesquisar = new javax.swing.JButton();
        JBAtualizar = new javax.swing.JButton();
        JBExcluir = new javax.swing.JButton();
        JBNovo = new javax.swing.JButton();
        JBVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JLTitulo.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        JLTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/locadora.png"))); // NOI18N
        JLTitulo.setText("Locadora Castellano");

        JLSubTitulo.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        JLSubTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/cliente.png"))); // NOI18N
        JLSubTitulo.setText("Clientes");

        JTabela.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "CPF", "Nome", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTabela);

        JLCpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLCpf.setText("CPF:");

        JBPesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/pesquisar.png"))); // NOI18N
        JBPesquisar.setText("Pesquisar");
        JBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPesquisarActionPerformed(evt);
            }
        });

        JBAtualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/atualizar.png"))); // NOI18N
        JBAtualizar.setText("Alterar");
        JBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAtualizarActionPerformed(evt);
            }
        });

        JBExcluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/excluir.png"))); // NOI18N
        JBExcluir.setText("Excluir");
        JBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBExcluirActionPerformed(evt);
            }
        });

        JBNovo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/novo.png"))); // NOI18N
        JBNovo.setText("Novo");
        JBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNovoActionPerformed(evt);
            }
        });

        JBVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/icons/voltar.png"))); // NOI18N
        JBVoltar.setText("Voltar");
        JBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBNovo)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBVoltar)
                            .addComponent(JBAtualizar))
                        .addGap(28, 28, 28)
                        .addComponent(JBExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(JBPesquisar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(JLSubTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JLTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLSubTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLCpf)
                    .addComponent(JTCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBAtualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JBNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(JBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVoltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_JBVoltarActionPerformed

    private void JBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNovoActionPerformed
        CadastrarCliente tela = new CadastrarCliente();
        tela.setVisible(true);
    }//GEN-LAST:event_JBNovoActionPerformed

    private void JBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPesquisarActionPerformed
        if("".equals(JTCpf.getText())){            
            try {
                preencheTable();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ListCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            DefaultTableModel dftm = (DefaultTableModel) JTabela.getModel();

            while (dftm.getRowCount() > 0) {
                dftm.removeRow(0);
            }

            try {
                String cpf = JTCpf.getText();
                Cliente cliente = new ClienteDAO().buscarPeloCPF(cpf);
                listaClientes = new ArrayList<Cliente>();
                listaClientes.add(cliente);

                if(cliente == null || cliente.getId() == 0){
                    JOptionPane.showMessageDialog(null, "Nenhum cliente encontrado por esse cpf");
                }
                else{
                    for (Cliente c : listaClientes) {
                        String[] coluna = new String[5];
                        coluna[0] = c.getId() + "";
                        coluna[1] = c.getCpf();
                        coluna[2] = c.getNome();
                        coluna[3] = c.getEndereco();
                        dftm.addRow(coluna);
                    }
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao buscar o cliente: " + ex.getMessage());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ListCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_JBPesquisarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            preencheTable();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ListCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void JBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAtualizarActionPerformed
        final int idx = JTabela.getSelectedRow();

        if (idx < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente!!!");
        } else {
            CadastrarCliente tela = new CadastrarCliente();
            tela.preparedEdit(listaClientes.get(idx), "Editar");
            tela.setVisible(true);       
        }
    }//GEN-LAST:event_JBAtualizarActionPerformed

    private void JBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBExcluirActionPerformed
        final int idx = JTabela.getSelectedRow();

        if (idx < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente!!!");
        } else {
            Cliente cliente = listaClientes.get(idx);    
            ClienteDAO clienteDAO = new ClienteDAO();
            
            try {
                clienteDAO.apagar(cliente);
                listaClientes.remove(idx);
                JOptionPane.showMessageDialog(null, "Operção realizada com sucesso!!!");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }            
        }
    }//GEN-LAST:event_JBExcluirActionPerformed

    
    private void preencheTable() throws ClassNotFoundException {
        DefaultTableModel dftm = (DefaultTableModel) JTabela.getModel();

        while (dftm.getRowCount() > 0) {
            dftm.removeRow(0);
        }

        try {
            listaClientes = new ClienteDAO().buscarTodos();
            for (Cliente c : listaClientes) {
                String[] coluna = new String[5];
                coluna[0] = c.getId() + "";
                coluna[1] = c.getCpf();
                coluna[2] = c.getNome();
                coluna[3] = c.getEndereco();
                dftm.addRow(coluna);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar os clientes");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAtualizar;
    private javax.swing.JButton JBExcluir;
    private javax.swing.JButton JBNovo;
    private javax.swing.JButton JBPesquisar;
    private javax.swing.JButton JBVoltar;
    private javax.swing.JLabel JLCpf;
    private javax.swing.JLabel JLSubTitulo;
    private javax.swing.JLabel JLTitulo;
    private javax.swing.JTextField JTCpf;
    private javax.swing.JTable JTabela;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    
    private ArrayList<Cliente> listaClientes;

}
